# Change this value to your own domain.
base_url = "knownunown.github.io/my-nice-cool-personal-site"

title = ""
description = ""

# minify_html = true
compile_sass = true

[extra]
author = "andrew"
menu = [
    { url = "/", name = "Home" },
    { url = "https://bigrat.monster", name = "Big Rat Monster" },
]
